const API_PATH = {
    REG_ACC: "/reg",
    LOGIN: "/auth/login",
    PROFILE_BY_ID: "/api/profile/:profileId",
    SET_PROFILE_BY_ID: "/api/profile/edit/:profileId",
    CREATE_CLASS: "/api/classes/create",
    ADD_MEMBER_CLASS: "/api/classes/:classId/members/add",
    DELETE_MEMBER_CLASS: "/api/classes/:classId/members/delete",
    MY_CLASS_MEMBERS_INFORS: "/api/classes/:classId/members/infors",
    GET_CLASS_BY_ID : "/api/classes/:classId",
    POST_TO_FEED : "/api/classes/:classId/feed/add",
    GET_POST_BY_ID: "/api/classes/:classId/feed/:postId",
    GET_ALL_POSTS: "/api/classes/:classId/feed/posts/get",
    COMMENT_TO_POST: "/api/classes/:classId/feed/:postId/comments/add",
    GET_COMMENT_POST: "/api/classes/:classId/feed/:postId/comments/get",
    RECENT_CHAT: "/api/chat/recent",
    RECENT_CONTACT: "/api/chat/recentcontact",
    MESSAGES_BY_VNU_ID: "/api/chat/:otherVNUId",
    ADD_SUBJECT: "/api/subjects/add",
    UPLOAD_DSSV : "/api/upload/dssv",
    UPLOAD_DSSV_CLASS : "/api/classes/:classId/members/import",
    UPLOAD_DSCV : "/api/upload/dscv",
    UPLOAD_DSMH: "/api/upload/dsmh",
    UPLOAD_SV_MH_SCORE : "/api/scores/import",
    UPLOAD_FILE : "/api/upload/file",
    ADD_SCORE_BY_VNU_ID: "/api/scores/add",
    GET_SCORES_BY_ID : "/api/scores/:userId",
    PUBLIC_DATA: "/public/data/:filename",
    LIKE_POST: "/api/classes/:classId/feed/:postId/likes/toogle",
    UPLOAD_COURSE:"/api/upload/course",
    ADMIN_ADD_COURSE: "/api/admin/addcourse",
    ADMIN_ADD_CLASS: "/api/admin/addclass",
    GET_CLASS_BY_TEACHER_ID: "/api/classes/teacher/:teacherId",
    UPLOAD_CLASS: "/api/upload/class",
    GET_CLASS_DETAIL: "/api/classes/:classId/details",
    GET_CLASS_BY_STUDENT_ID: "/api/classes/Student/:studentId",

    CREATE_TEST: "/api/classes/:classId/tests",
    GET_TEST_DETAIL: "/api/tests/:testId",
    UPDATE_TEST: "/api/tests/:testId",
    DELETE_TEST: "/api/tests/:testId",
    GET_CLASS_TESTS: "/api/classes/:classId/tests",
    PUBLIC_TEST: "/api/tests/:testId/publish",
    CREATE_QUESTION: "/api/tests/:testId/questions",
    GET_QUESTION: "/api/tests/:testId/questions/:questionId",
    UPDATE_QUESTION: "/api/tests/:testId/questions/:questionId",
    DELETE_QUESTION: "/api/tests/:testId/questions/:questionId",
    GET_TEST_QUESTIONS: "/api/tests/:testId/questions",
    GET_TEST_BY_STUDENT: "/api/tests/:testId/Student/:studentId",
    SUBMIT_TEST_BT_STUDENT: "/api/tests/:testId/Student/:studentId/submit",
    GET_STUDENTS_TEST_RESULT: "/api/tests/:testId/results",
    GET_STUDENT_TEST_RESULT: "/api/tests/:testId/results/:studentId",

    CREATE_NOTIFICATION: '/api/classes/:classId/notifications',
    GET_CLASS_NOTIFICATIONS: '/api/classes/:classId/notifications',
    GET_NOTIFICATION_DETAIL: '/api/classes/:classId/notifications/:notificationId',
    MARK_NOTIFICATION_AS_READ: '/api/classes/:classId/notifications/:notificationId/read'
};
const HOST_NAME = "http://localhost:3000";
export {API_PATH, HOST_NAME};